const CREATED_CODE = 201;
const ERROR_BAD_REQUEST = 400;
const ERROR_NOTAUTHORIZED = 401;
const ERROR_FORBIDDEN = 403;
const ERROR_NOT_FOUND = 404;
const ERROR_CONFLICT = 409;
const ERROR_SERVER = 500;

module.exports = {
  CREATED_CODE,
  ERROR_BAD_REQUEST,
  ERROR_NOTAUTHORIZED,
  ERROR_FORBIDDEN,
  ERROR_NOT_FOUND,
  ERROR_CONFLICT,
  ERROR_SERVER,
};
